set nu
set ts=4
set sw=4
set enc=utf-8
set nocompatible
set nobackup
set undodir=~/vimfiles/undodir
set fileencodings=ucs-bom,utf-8,gb18030,latin1
source $VIMRUNTIME/vimrc_example.vim

if !isdirectory(&undodir)
	call mkdir(&undodir, 'p', 0700)
endif

if has('mouse')
	if has('gui_running') || (&term=~ 'xterm' && !has('mac'))
		set mouse=a
	else
		set mouse=nvi
	endif
endif

if has('gui_running')
	set guifont=Consolas:h15
endif
