set nu
set ts=4
set sw=4
set enc=utf-8
set nocompatible
set nobackup
set undodir=~/vimfiles/undodir
set fileencodings=ucs-bom,utf-8,gb18030,latin1
source $VIMRUNTIME/vimrc_example.vim

if !isdirectory(&undodir)
	call mkdir(&undodir, 'p', 0700)
endif

" 鼠标的配置
if has('mouse')
	if has('gui_running') || (&term=~ 'xterm' && !has('mac'))
		set mouse=a
	else
		set mouse=nvi
	endif
endif

" 字体的配置
if has('gui_running')
	set guifont=Consolas:h15
endif

if exists('*minpac#init')
	" Minpac is loaded.
	call minpac#init()
	call minpac#add('k-takata/minpac', {'type': 'opt'})
	" Other plugins
	call minpac#add('tpope/vim-eunuch')
endif


if exists('g:loaded_minpac')
  " Minpac is loaded.
  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})
  " Other plugins
  call minpac#add('tpope/vim-eunuch')
  call minpac#add('yegappan/mru')
  call minpac#add('preservim/nerdtree')
endif

if has('eval')
  " Minpac commands
  command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update()
  command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
  command! PackStatus packadd minpac | source $MYVIMRC | call minpac#status()
endif


if !has('gui_running')
  " 设置文本菜单
  if has('wildmenu')
    set wildmenu
    set cpoptions-=<
    set wildcharm=<C-Z>
    nnoremap <F10>      :emenu <C-Z>
    inoremap <F10> <C-O>:emenu <C-Z>
  endif
endif

" 终端模式下的复制，解决格式对齐问题
if !has('patch-8.0.210')
	" 进入插入模式时启用括号粘贴模式
	let &t_SI .= "\<Esc>[?2004h"
	" 退出插入模式时停用括号粘贴模式
	let &t_EI .= "\<Esc>[?2004l"
	" 见到 <Esc>[200~ 就调用 XTermPasteBegin
	inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

	function! XTermPasteBegin()
		" 设置使用 <Esc>[201~ 关闭粘贴模式
		set pastetoggle=<Esc>[201~
		" 开启粘贴模式
		set paste
		return ""
	endfunction
endif

if v:version >= 800
	packadd! editexisting
endif

" 映射快捷键ctrl+Tab 切换tab页
nnoremap <C-Tab> <C-W>w
inoremap <C-Tab> <C-O><C-W>w
nnoremap <C-S-Tab> <C-W>w
inoremap <C-S-Tab> <C-O><C-W>w
